### ISSUE TITLE
Constraining output of log_std in SAC

### ISSUE THREAD

**Issue by henrycharlesworth** [openai/spinningup#108]
Just a bit confused about a section of the SAC implementation (core.py). It says "...To protect against that, we'll constrain the output range of the log_stds, to lie within [LOG_STD_MIN, LOG_STD_MAX]. This is slightly different from the trick used by the authors of SAC---they used tf.clip_by_value instead of squashing and rescaling".

Then we have:

log_std = LOG_STD_MIN + 0.5* (LOG_STD_MAX - LOG_STD_MIN) * (log_std + 1)

As far as I can see this definitely does not constrain the value of log_std to be within [LOG_STD_MIN, LOG_STD_MAX]. Am I missing something here?

**Comment by mch5048** [comment]
I think it's simple mathematics.
Since tanh activated output of the log_std layer is in range (-1,1), and we want it to be transformed into [MIN,MAX]. 
Let the transformation be linear as OUT = a*IN + b.
we know two pairs of soln (IN,OUT) = (-1,MIN) & (1,MAX). 
Then, a+b = MAX and -a+b = MIN -> b= (MIN+MAX)/2 , a = (MAX-MIN)/2
by some modification , we have  OUT = MIN + (MAX-MIN)(IN+1)/2 which equals to the implementation
`log_std = LOG_STD_MIN + 0.5 * (LOG_STD_MAX - LOG_STD_MIN) * (log_std + 1)` 

Let me know if I'm understanding it wrong.

**Comment by mch5048** [comment]
I think you missed the nonlinearity tanh part in spinup implementation
`    log_std = tf.layers.dense(net, act_dim, activation=tf.tanh)`

**Comment by henrycharlesworth** [comment]
Thank you very much, I see now!
