### ISSUE TITLE
Why performance metric of on-policy methods use training trajectories ?

### ISSUE THREAD

**Issue by zuoxingdong** [openai/spinningup#11]
Would it be more fair to evaluate the policy for certain trajectories on certain training intervals?

**Comment by jachiam** [comment]
Hi @zuoxingdong,

The normal train/test distinction from supervised learning doesn't usually exist in RL. The reason that there's a "test" distinction in the off-policy methods is because, in off-policy methods, we are separately evaluating the **behavior policy** and the **learned policy.** The behavior policy is typically the learned policy plus noise.

By contrast, the on-policy methods do not have a distinction between behavior policy and learned policy: you act in the environment, always, with the most recent learned policy. So the batch of trajectories sampled according to the current policy is suitable for evaluating.

**Comment by jachiam** [comment]
Leaving this open in case you (or anyone else) had any additional questions.

**Comment by zuoxingdong** [comment]
@machinaut @jachiam Hi, thanks a lot for the detailed explanations. I agree with the idea that for on-policy methods, it is sufficient to use returns from collected training trajectories for an empirical estimate of the policy performance. There are follow-up questions that comes to my mind:

If I got it right, e.g. current VPG implementation collects full episodic transitions (say 1k time steps for Mujoco) for each policy update. In practice, sometime people also use another orthogonal implementation which takes T timesteps instead of full episode (e.g. 200 time steps). 
    - Is it discouraged to do like this, because I guess it makes part of information in environment never accessible to agent, and also it will then require an independent evaluation to take full trajectories. 
    - Taking full episode transitions (e.g. 1k time steps, batch size 4 for each epochs), it means each policy update involves returns from 4 episodes for current policy. In the docs, the performance metric is an averaged return of recent 100 episodes, so when we use this for plotting performance curves with x-axis either iterations or timesteps, is it okay that the y-value is in fact a running average of returns that involves several old policies, and in this case, the returns from current policy has importance of only 4 out of 100 ?
    - After some empirical experiments, I observe that for some certain experiments, agent can benefits from taking shorter timesteps than full episode for policy update. Say both training with 1e6 timesteps, sometimes former has better final performance than latter. I guess the reason is just because the former  can have more gradient updates, but it doesn't resolve the problem when environment needs longer timesteps to complete a task, the former will never be able to do it.

**Comment by jachiam** [comment]
Re: using shorter episode lengths: whether or not this is discouraged depends on the setting. You could try to research a variant of an RL problem where you do, in fact, care about generalizations to time horizons beyond what you train on---in which case it's perfectly reasonable. But this is not "default" for RL.

[Spinning Up's logger](https://spinningup.openai.com/en/latest/utils/logger.html) behaves differently from Baselines or Gym logger: it only reports the average return from the current batch of trajectories, not the preceding 100. Also, it only includes returns from trajectories that have finished during the current batch---if a trajectory gets cut off by the end of epoch, it is not included in the calculation.

It's true that sometimes the agent benefits from shorter timesteps than full episode. It's not just about more gradient steps---it's also because resets contain valuable information for the agent (eg, in some of the MuJoCo envs, resets get the agent back to a standing position, which has a positive bias for running).
