### ISSUE TITLE
Why use two optimizers for DDPG when one is sufficient?

### ISSUE THREAD

**Issue by Solliet** [openai/spinningup#210]
https://github.com/openai/spinningup/blob/ed725b36023e37d9bfd5e3d70f381750ee305784/spinup/algos/pytorch/ddpg/ddpg.py#L186-L188

```python
optimizer = Adam([
      dict(params=ac.q.parameters(), lr=q_lr),
      dict(params=ac.pi.parameters(), lr=pi_lr)
]) 
```

**Comment by jachiam** [comment]
Because whether or not one is sufficient depends on other details not local to this choice.

The policy learning objective depends on parameters for both pi and Q. If you don't explicitly turn off gradient flow for Q (by setting .requires_grad = False), gradients will accumulate to Q when you take a backward pass through that objective. If you were to use a single Adam optimizer for both pi and Q under these conditions, Q will get destructive updates from the pi update. Using two optimizers is just safer as a result: it precludes the possibility of this somewhat-invisible bug.

**Comment by Solliet** [comment]
Ah I am terribly sorry, I was under the impression that `q.train(mode=False)` disabled the accumulation of gradients, but after manually checking it. I was wrong. You also can't use 

```Python
q.requires_grad_(False)
q(x).mean().backward()
```
Because it can't compute the grads from Q, so using two optimizers makes a lot of sense. Thanks and sorry for the taking your time.

**Comment by jachiam** [comment]
Not a waste of time at all! Glad to have helped.

Also---I think you could do the latter thing (turn off requires_grad, and then do the update without issue), but again, it's a pattern that makes risk of a bug higher.

**Comment by Solliet** [comment]
I tested it with a sequential model and I am getting this:

```
>>> m = m.requires_grad_(False)
>>> m(x).mean().backward()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stelios/anaconda3/envs/thesis/lib/python3.7/site-packages/torch/tensor.py", line 166, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/stelios/anaconda3/envs/thesis/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

So it seems unlikely unless I am missing something again. Thanks for the help. It explains why my implementation never learnt.. hah.
