### ISSUE TITLE
Soft Actor-Critic: is Q2 redundant in current implementation?

### ISSUE THREAD

**Issue by lostmsu** [openai/spinningup#213]
I am unable to find any place in the code, where Q1 and Q2 would be used asymmetrically, which makes me think: is Q2 completely redundant?

**Comment by jachiam** [comment]
It's hard to say. It's the sort of thing that could benefit from deeper ablation analysis. My guess is that it isn't redundant all the time---I think it staves off some overestimation issues that would otherwise arise early in training. But, I also suspect that it becomes useless later in training, as Q1 and Q2 converge towards each other.

I recommend you try out some experiments where you remove it and see what happens.
