### ISSUE TITLE
Roboschool support

### ISSUE THREAD

**Issue by Guitaricet** [openai/spinningup#35]
Hi!
Any changes spinningup is going to support Roboschool as an alternative to MuJoCo?

**Comment by jachiam** [comment]
Hi @Guitaricet,

The answer is a bit mixed.

**It sort of already does:** Spinning Up implementations work with any environments that are registered with Gym and have continuous, vector-valued observations. So to use Roboschool envs with Spinning Up, you would first [install Roboschool](https://github.com/openai/roboschool/blob/master/README.md), and then you could just use Roboschool envs with Spinning Up implementations the same way you would use Gym envs (because `import roboschool` registers the Roboschool envs with Gym). Spinning Up wouldn't support this by default from the command line, but you can easily change that by adding `import roboschool` to `spinup/__init__.py`---at which point you could specify Roboschool envs from the command line the same as any other Gym envs.

**But dedicated support is a higher bar.** Right now, MuJoCo envs are integrated into Spinning Up in four main ways: 

1. They are available through Gym as training envs for the algorithms.

2. We put in special effort, leading up to this release, to smooth out the MuJoCo installation process.

3. The MuJoCo envs are used as the algorithm benchmarks, with default hyperparameters tuned to be reasonable for MuJoCo.

4. The MuJoCo envs are used in several exercises.

At the moment, Roboschool can clear the first bar (because the envs are usable with the algorithms as long as you've installed Roboschool). However, there's a nontrivial amount of work that would go into replacing MuJoCo with Roboschool for the others. We're thinking seriously about how we could get there, but we may not have a fast decision: it depends on how internal development goes.

**Comment by Guitaricet** [comment]
Thank you @jachiam for such a detailed answer!

**Comment by erwincoumans** [comment]
PyBullet is recommended over Roboschool, and it has a wider variety of Gym environments, easier to install and more features. See the [PyBullet documentation](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.2ye70wns7io3). Installation is simply 'pip install pybullet'.
