### ISSUE TITLE
Issue with the order of updates operation in SAC ?

### ISSUE THREAD

**Issue by unrealwill** [openai/spinningup#45]
I think there is an issue with the order of updates operation in SAC.

In sac.py L191
```
with tf.control_dependencies([train_pi_op]):
        train_value_op = value_optimizer.minimize(value_loss, var_list=value_params)
```

We update the policy parameters, before we update the value parameters.
In the paper https://spinningup.openai.com/en/latest/_images/math/7ff0536d2e479ae833174c13ccff07b043d7cb55.svg
it is the opposite order. 

If I understand the paper update scheme (an application of Gibbs sampling), it intends to compute Q using old P weight, then compute the update of P using updated Q weights. 

Mathematically  you probably can do it in the opposite order but you must use an old weight then an updated weight. 
This means that if you do it first P then Q the targets computations must use updated weights for P when updating Q (invoke the actor_critic function and compute the targets inside the tf.control_dependencies block (specifically the term **logp_pi** inside yv) ).

The control dependencies don't recompute all dependent operations  as the following code helps understand.

```
import tensorflow as tf

x = tf.Variable(0.0)

targetx = 3 * x 
updatex = tf.assign(x,x+1)

with( tf.control_dependencies([updatex]) ):
    res = targetx

sess = tf.Session()
sess.run(tf.global_variables_initializer())
print( sess.run( res ) ) #print 0 targetx is not recomputed
```

**Comment by jachiam** [comment]
Hi @unrealwill,

I'm not sure that this is actually a problem. As implemented, the updates are effectively simultaneous (despite the control dep, as you point out, the update to P does not change the targets for Q and V---meaning that it does not effect their updates). This is reasonable, even though the logic of the algorithm may seem to motivate something slightly different.

I picked this arrangement for control deps because of what is admittedly a limitation on my part: I wanted all of the ops to happen in one sess.run for speed, and I wasn't sure how TF would handle the policy update under the hood if the dependency went the other way (in particular, I was concerned that the forward pass through Q_pi would use the old Q params, and the backward pass would use the updated Q params while still using activations from the forward pass with the old Q params, which wouldn't make sense). 

I suspect that the version you're suggesting would not make a substantial difference in the performance of the algorithm. Using updated P params would not change the Q target, it would only change the V target. And changes to V only influence Q and P through V_targ, which updates from V on a lag. So this would add a one-update-lead to something that is quite slow, and one update does not make a huge difference.

I recommend that you try out this version. You could do it by breaking the single `outs = sess.run(step_ops, feed_dict)` into two `sess.run`s, one which updates Q and V, and then one which updates P. Give it a shot and let me know if performance is any different.

**Comment by unrealwill** [comment]
That's a "best fixed with a comment" kind of bug.

It is indeed a very tempting approximation to make. You get roughly 2x the speed and the term is not so different. 

"one update does not make a huge difference" : what matter in deep learning is how much bias it has, as this will accumulate over iterations. Anything not bias-less spoils convergence guarantees (which usually mean in practice that better optimizer and larger steps don't work as well).

That's a bias-speed tradeoff which is probably justified though, but that something that may come back later to bite you. It has the same vibe as those Spectre/Meltdown attacks, doing something wrong, getting a huge payoff in terms of performance, getting exposed but still wanting to do it nonetheless :)

**Comment by jachiam** [comment]
For SAC in the function approximation setting, I'm reasonably sure that there are no convergence guarantees to spoil. The proof in the SAC paper is for soft policy iteration, which only works when you can exactly evaluate the soft policy evaluation step, which is not generally possible in the function approximation setting. Q-learning with nonlinear function approximation, bootstrapping, and experience replay, to my knowledge, has no known convergence guarantees, and there are some specific-case counterexamples.

I'll also note that it's a faithful replication of SAC as implemented by the original authors ([here](https://github.com/haarnoja/sac/blob/master/sac/algos/sac.py#L368) is where they do training in their code---also one op, although they omit control deps).

Disagreement aside, on a personal note, I am generally pretty impressed with the quality of your questions and comments. I'd be interested to have a longer discussion with you at some point---drop me a line in an email? jachiam at openai.com.
